spring.application.name=routesync-backend

# Server
server.port=5000


# =====================================================
# RouteSync OTP Configuration
# =====================================================

# OTP length
routesync.otp.length=6

# OTP validity = 5 minutes
routesync.otp.expiration=300000

# Resend cooldown = 60 seconds
routesync.otp.resend-cooldown=60000