spring.application.name=routesync-backend

# Server
server.port=5000

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/routesync
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.web=TRACE
logging.level.org.springframework.security.authorization=TRACE

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# =====================================================
# RouteSync JWT Configuration
# =====================================================

# JWT secret
# IMPORTANT:
# Production mein is value ko environment variable se provide karna.
routesync.jwt.secret=${JWT_SECRET}

# ==========================================
# Email CONFIGURATION
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${ROUTESYNC_MAIL_USERNAME}
spring.mail.password=${ROUTESYNC_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ==========================================
# TWILIO SMS CONFIGURATION
# ==========================================

routesync.twilio.account-sid=${TWILIO_ACCOUNT_SID}
routesync.twilio.auth-token=${TWILIO_AUTH_TOKEN}
routesync.twilio.from-number=${TWILIO_FROM_NUMBER}


# Access token validity
# 15 minutes = 900000 milliseconds
# 4 hour = 14,400,000 milliseconds
routesync.jwt.access-token-expiration=14400000

# Refresh token validity
# 7 days = 604800000 milliseconds
routesync.jwt.refresh-token-expiration=604800000