spring.application.name=routesync-backend

# Server
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/routesync
spring.datasource.username=postgres
spring.datasource.password=${DB_Password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# =====================================================
# RouteSync JWT Configuration
# =====================================================

# JWT secret
# IMPORTANT:
# Production mein is value ko environment variable se provide karna.
routesync.jwt.secret=${JWT_SECRET}

# Access token validity
# 15 minutes = 900000 milliseconds
routesync.jwt.access-token-expiration=900000

# Refresh token validity
# 7 days = 604800000 milliseconds
routesync.jwt.refresh-token-expiration=604800000